[package]
name = "kiril/clear-dnipro-project-roblox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1"
Janitor = "howmanysmall/janitor@^1.15.7"
BufferUtil = "sleitnick/buffer-util@0.3.0"
Comm = "sleitnick/comm@1.0.1"
Component = "sleitnick/component@2.4.8"
Concur = "sleitnick/concur@0.1.2"
EnumList = "sleitnick/enum-list@2.1.0"
Input = "sleitnick/input@2.3.0"
Loader = "sleitnick/loader@2.0.0"
Log = "sleitnick/log@0.1.1"
Net = "sleitnick/net@0.2.0"
Option = "sleitnick/option@1.0.5"
PID = "sleitnick/pid@2.1.0"
Quaternion = "sleitnick/quaternion@0.2.3"
Sequent = "sleitnick/sequent@0.1.0"
Ser = "sleitnick/ser@1.0.5"
Shake = "sleitnick/shake@0.1.7"
Signal = "sleitnick/signal@2.0.1"
Silo = "sleitnick/silo@0.2.0"
Streamable = "sleitnick/streamable@1.2.4"
TableUtil = "sleitnick/table-util@1.2.1"
TaskQueue = "sleitnick/task-queue@1.0.0"
Timer = "sleitnick/timer@1.1.2"
Tree = "sleitnick/tree@1.1.0"
Trove = "sleitnick/trove@1.2.0"
WaitFor = "sleitnick/wait-for@1.0.0"